<?php
//list of countries
global $country_array;
$country_array = array();
/*$country_array["AF"]="Afghanistan";
$country_array["AL"]="Albania";
$country_array["DZ"]="Algeria";
$country_array["AS"]="American Samoa";
$country_array["AD"]="Andorra";
$country_array["AO"]="Angola";
$country_array["AI"]="Anguilla";
$country_array["AG"]="Antigua and Barbuda";*/
$country_array["Argentina"]="Argentina";
/*$country_array["AM"]="Armenia";
$country_array["AW"]="Aruba";*/
$country_array["Australia"]="Australia";
$country_array["Austria"]="Austria";
/*$country_array["AZ"]="Azerbaijan";
$country_array["BS"]="Bahamas";
$country_array["BH"]="Bahrain";
$country_array["BD"]="Bangladesh";
$country_array["BB"]="Barbados";
$country_array["BY"]="Belarus";*/
$country_array["Belgium"]="Belgium";
$country_array["Belize"]="Belize";
/*$country_array["BJ"]="Benin";
$country_array["BM"]="Bermuda";
$country_array["BT"]="Bhutan";
$country_array["BO"]="Bolivia";
$country_array["BA"]="Bosnia and Herzegovina";*/
$country_array["Botswana"]="Botswana";
//$country_array["BV"]="Bouvet Island";
$country_array["Brazil"]="Brazil";
/*$country_array["IO"]="British Indian Ocean Territory";
$country_array["VG"]="British Virgin Islands";
$country_array["BN"]="Brunei";
$country_array["BG"]="Bulgaria";
$country_array["BF"]="Burkina Faso";
$country_array["BI"]="Burundi";
$country_array["KH"]="Cambodia";
$country_array["CM"]="Cameroon";*/
$country_array["Canada"]="Canada";
/*$country_array["CV"]="Cape Verde";
$country_array["KY"]="Cayman Islands";
$country_array["CF"]="Central African Republic";
$country_array["TD"]="Chad";*/
$country_array["Chile"]="Chile";
$country_array["China"]="China";
/*$country_array["CX"]="Christmas Island";
$country_array["CC"]="Cocos (Keeling) Islands";
$country_array["CO"]="Colombia";
$country_array["KM"]="Comoros";
$country_array["CG"]="Congo";
$country_array["CD"]="Congo - Democratic Republic of";
$country_array["CK"]="Cook Islands";*/
$country_array["Costa Rica"]="Costa Rica";
/*$country_array["CI"]="Cote d'Ivoire";
$country_array["HR"]="Croatia";*/
$country_array["Cuba"]="Cuba";
/*$country_array["CY"]="Cyprus"; */
$country_array["Czech Republic"]="Czech Republic";
$country_array["Denmark"]="Denmark";
/*$country_array["DJ"]="Djibouti";
$country_array["DM"]="Dominica";*/
$country_array["Dominican Republic"]="Dominican Republic";
/*$country_array["TP"]="East Timor";*/
$country_array["Ecuador"]="Ecuador";
$country_array["Egypt"]="Egypt";
/*$country_array["SV"]="El Salvador";
$country_array["GQ"]="Equitorial Guinea";
$country_array["ER"]="Eritrea";
$country_array["EE"]="Estonia";
$country_array["ET"]="Ethiopia";
$country_array["FK"]="Falkland Islands (Islas Malvinas)";
$country_array["FO"]="Faroe Islands";
$country_array["FJ"]="Fiji";*/
$country_array["Finland"]="Finland";
$country_array["France"]="France";
/*$country_array["GF"]="French Guyana";
$country_array["PF"]="French Polynesia";
$country_array["TF"]="French Southern and Antarctic Lands";
$country_array["GA"]="Gabon";
$country_array["GM"]="Gambia";
$country_array["GZ"]="Gaza Strip";
$country_array["GE"]="Georgia";*/
$country_array["Germany"]="Germany";
$country_array["Ghana"]="Ghana";
/*$country_array["GI"]="Gibraltar";*/
$country_array["Greece"]="Greece";
/*$country_array["GL"]="Greenland";
$country_array["GD"]="Grenada";
$country_array["GP"]="Guadeloupe";
$country_array["GU"]="Guam";*/
$country_array["Guatemala"]="Guatemala";
/*$country_array["GN"]="Guinea";
$country_array["GW"]="Guinea-Bissau";
$country_array["GY"]="Guyana";
$country_array["HT"]="Haiti";
$country_array["HM"]="Heard Island and McDonald Islands";
$country_array["VA"]="Holy See (Vatican City)";
$country_array["HN"]="Honduras";
$country_array["HK"]="Hong Kong";*/
$country_array["Hungary"]="Hungary";
/*$country_array["IS"]="Iceland";*/
$country_array["India"]="India";
/*$country_array["ID"]="Indonesia";
$country_array["IR"]="Iran";
$country_array["IQ"]="Iraq";*/
$country_array["Ireland"]="Ireland";
$country_array["Israel"]="Israel";
$country_array["Italy"]="Italy";
/*$country_array["JM"]="Jamaica";*/
$country_array["Japan"]="Japan";
$country_array["Jordan"]="Jordan";
/*$country_array["KZ"]="Kazakhstan";*/
$country_array["Kenya"]="Kenya";
/*$country_array["KI"]="Kiribati";
$country_array["KW"]="Kuwait";
$country_array["KG"]="Kyrgyzstan";
$country_array["LA"]="Laos";
$country_array["LV"]="Latvia";
$country_array["LB"]="Lebanon";
$country_array["LS"]="Lesotho";
$country_array["LR"]="Liberia";
$country_array["LY"]="Libya";
$country_array["LI"]="Liechtenstein";
$country_array["LT"]="Lithuania";
$country_array["LU"]="Luxembourg";
$country_array["MO"]="Macau";
$country_array["MK"]="Macedonia - The Former Yugoslav Republic of";
$country_array["MG"]="Madagascar";
$country_array["MW"]="Malawi";
$country_array["MY"]="Malaysia";
$country_array["MV"]="Maldives";
$country_array["ML"]="Mali";
$country_array["MT"]="Malta";
$country_array["MH"]="Marshall Islands";
$country_array["MQ"]="Martinique";
$country_array["MR"]="Mauritania";
$country_array["MU"]="Mauritius";
$country_array["YT"]="Mayotte";*/
$country_array["Mexico"]="Mexico";
/*$country_array["FM"]="Micronesia - Federated States of";
$country_array["MD"]="Moldova";
$country_array["MC"]="Monaco";
$country_array["MN"]="Mongolia";
$country_array["MS"]="Montserrat";*/
$country_array["Morocco"]="Morocco";
/*$country_array["MZ"]="Mozambique";
$country_array["MM"]="Myanmar";
$country_array["NA"]="Namibia";
$country_array["NR"]="Naura";
$country_array["NP"]="Nepal";*/
$country_array["Netherlands"]="Netherlands";
/*$country_array["AN"]="Netherlands Antilles";
$country_array["NC"]="New Caledonia";*/
$country_array["New Zealand"]="New Zealand";
$country_array["Nicaragua"]="Nicaragua";
/*$country_array["NE"]="Niger";
$country_array["NG"]="Nigeria";
$country_array["NU"]="Niue";
$country_array["NF"]="Norfolk Island";
$country_array["KP"]="North Korea";
$country_array["MP"]="Northern Mariana Islands";*/
$country_array["Norway"]="Norway";
/*$country_array["OM"]="Oman";
$country_array["PK"]="Pakistan";
$country_array["PW"]="Palau";
$country_array["PA"]="Panama";
$country_array["PG"]="Papua New Guinea";
$country_array["PY"]="Paraguay";*/
$country_array["Peru"]="Peru";
/*$country_array["PH"]="Philippines";
$country_array["PN"]="Pitcairn Islands";
$country_array["PL"]="Poland";*/
$country_array["Portugal"]="Portugal";
/*$country_array["PR"]="Puerto Rico";
$country_array["QA"]="Qatar";
$country_array["RE"]="Reunion";
$country_array["RO"]="Romania";*/
$country_array["Russia"]="Russia";
/*$country_array["RW"]="Rwanda";
$country_array["KN"]="Saint Kitts and Nevis";
$country_array["LC"]="Saint Lucia";
$country_array["VC"]="Saint Vincent and the Grenadines";
$country_array["WS"]="Samoa";
$country_array["SM"]="San Marino";
$country_array["ST"]="Sao Tome and Principe";
$country_array["SA"]="Saudi Arabia";
$country_array["SN"]="Senegal";
$country_array["CS"]="Serbia and Montenegro";
$country_array["SC"]="Seychelles";
$country_array["SL"]="Sierra Leone";
$country_array["SG"]="Singapore";
$country_array["SK"]="Slovakia";
$country_array["SI"]="Slovenia";
$country_array["SB"]="Solomon Islands";
$country_array["SO"]="Somalia";*/
$country_array["South Africa"]="South Africa";
/*$country_array["GS"]="South Georgia and the South Sandwich Islands";*/
$country_array["South Korea"]="South Korea";
$country_array["Spain"]="Spain";
/*$country_array["LK"]="Sri Lanka";
$country_array["SH"]="St. Helena";
$country_array["PM"]="St. Pierre and Miquelon";
$country_array["SD"]="Sudan";
$country_array["SR"]="Suriname";
$country_array["SJ"]="Svalbard";
$country_array["SZ"]="Swaziland";*/
$country_array["Sweden"]="Sweden";
$country_array["Switzerland"]="Switzerland";
/*$country_array["SY"]="Syria";
$country_array["TW"]="Taiwan";
$country_array["TJ"]="Tajikistan";
$country_array["TZ"]="Tanzania";*/
$country_array["Thailand"]="Thailand";
/*$country_array["TG"]="Togo";
$country_array["TK"]="Tokelau";
$country_array["TO"]="Tonga";
$country_array["TT"]="Trinidad and Tobago";
$country_array["TN"]="Tunisia";*/
$country_array["Turkey"]="Turkey";
/*$country_array["TM"]="Turkmenistan";
$country_array["TC"]="Turks and Caicos Islands";
$country_array["TV"]="Tuvalu";
$country_array["UG"]="Uganda";
$country_array["UA"]="Ukraine";
$country_array["AE"]="United Arab Emirates";*/
$country_array["United Kingdom"]="United Kingdom";
$country_array["United States"]="United States";
/*$country_array["VI"]="United States Virgin Islands";
$country_array["UY"]="Uruguay";
$country_array["UZ"]="Uzbekistan";
$country_array["VU"]="Vanuatu";
$country_array["VE"]="Venezuela";
$country_array["VN"]="Vietnam";
$country_array["WF"]="Wallis and Futuna";
$country_array["PS"]="West Bank";
$country_array["EH"]="Western Sahara";
$country_array["YE"]="Yemen";
$country_array["ZM"]="Zambia";
$country_array["ZW"]="Zimbabwe";*/
?>