<div id="actual_content">
    <h1 id="title">Housing Arrangements</h1>
    <div id="content_container">
        <p>Your place of residence in [@country] will become the main site of most of your cultural interaction. Where you choose to live in [@country] can determine to what level you will immerse yourself in [@nationality1] culture.</p>
        <div class="table_of_contents">
            <div class="toc_main">Contents:</div>
            <div class="toc_list">
                <ul>
                    <li><a href="#section1">Conflict Resolution</a></li>
                    <li><a href="#section2">Types of Housing</a></li>
                    <li><a href="#section3">Relevant Questions</a></li>
                    <li><a href="#section4">Checklist</a></li>
                    <li><a href="#section5">Resources</a></li>
                </ul>
            </div>
        </div>
        <p>The majority of your language practice and communication will not take place in the classroom, or even during your travels. Rather, most of it will happen at home in your residence. At your place of residence, you will experience the most intense and personal form of culture&ndash;sharing, as the locals you will live with become your family, friends and roommates.</p>
        <p>Just as it took getting used to living with your dorm or apartment roommate(s) in the United States, it will take just as much effort to adjust to your living situation in [@country]. Your place of residence in [@country] comes with challenges, perhaps even more challenges than you had to deal with when you lived with roommates at your U.S. home campus. You will face language and culture differences which can affect, for example, when a person eats a meal, what he or she eats, personal hygiene issues, study habits, likes and dislikes, etc. However, keep in mind that your own habits and views will also seem different to the person(s) you are living with in [@country].</p>
        <h2><a name="section1"></a>1. Conflict Resolution</h2>
        <p>When thinking about housing in [@country], the most important thing to remember is patience. Try to be patient with yourself as you try to adjust to living with others in [@country]. Also, try to be patient with those you live with, as they will be learning to adjust to you as well. In the chance that things just don&#39;t work out for you, or you just are not compatible with your roommates or host family, make sure your program offers you the right to change your place of residence. Ask your program&#39;s administrators about your rights in regards to switching places of residence, and whether or not an administrator can help you find alternate housing should you need it. Your program administrators can act as conflict mediators to help you and your roommates or host family resolve any issues troubling you. If at any time you find your housing unsafe, be clear with program administrators and explain to them why it is unsafe and that you need to change housing as soon as possible.</p>
        <h2><a name="section2"></a>2. Types of Housing</h2>
        <p>There are three main types of housing options in [@country]. However, not all programs will offer all three housing options. In many cases, you may only be offered one type of housing option. Also, your program may not provide housing at all, or may not be able to guarantee housing for you.</p>
        <p>The home&ndash;stay option places a student, or sometimes more than one student, into [@nationality1] household. The student lives with his/her host family and participates in aspects of family life like meals and chores.</p>
        <p>The residence hall/dorm option places a student into a single room, possibly with a roommate. Students often share a bathroom and sometimes have a meal plan with communal dining facilities.</p>
        <p>The apartment option places a student into a small apartment, usually with roommates. Often, a student is responsible for finding an apartment on his/her own. In an apartment, students have the most responsibilities and the fewest number of rules; they must buy and cook meals, do laundry, pay rent and utilities and set their own household rules regarding curfews, noise, overnight guests, doing the dishes, etc.</p>
        <ul>
            <li><strong>Home&ndash;stay</strong>
                <p>Home&ndash;stay host "families" come in many shapes and sizes. You may be living with a traditional family comprised of a mother, father, children and pets. You may live in a divorced household, a single&ndash;parent household, a household with young children or teenagers or college&ndash;age children who go to the same college or university where you will study. You may live with an elderly widow or grandparents. You may live in the city or the country, in a spacious house or in a humble apartment. You will probably want to ask your program's administrators to which kind of household and family you will be assigned. Program administrators should have screened all home&ndash;stay families and living environments, and they should be able to tell you the main facts about your home&ndash;stay family.</p>
                <ul>
                    <li><strong>Rules and Direction</strong>
                        <p>If your home&ndash;stay family has young children, the parents may feel like they have to protect you too. For this reason, they may seem over&ndash;protective or over&ndash;bearing. They may also have stricter rules about overnight guests, being home in time for dinner every night, and helping out with chores. If it has been awhile since you've lived at home, family life may come as a shock to you at first. You may feel you've lost your independence; you may feel rebellious when it comes to family rules, or feel like your host family doesn't treat you as an adult. On the other hand, not many people get the opportunity to experience the private family lifestyle of another country. Home&ndash;stay is a very special and unique experience where a family decides to open up and share its life with you. Also, a family's rules can help keep you out of trouble while you are learning to know your environment better. A family can give you advice on shopping and restaurants, directions to just
                            about everywhere, and a kind of caring that resembles the love your own family has for you.</p>
                    </li>
                    <li><strong>Privacy and Sharing</strong>
                        <p>In a home&ndash;stay environment, your business often becomes your "family's" business. Although you may have your own room in their house, chances are you will be watching television with your family, chatting at mealtimes, and attending family gatherings at holidays. You will get to know your family members and they will want to know things about you in return. Keep in mind that other cultures have different ideas of privacy and personal space. Even though you have your own room, it's still technically your family's room in your family's house. You may have the family's children or pets coming in and out of your room when you're trying to do your homework. On the other hand, your host "mother" may come in your room to change your bed sheets for you and deliver your freshly ironed and neatly folded laundry. Having overnight guests, or staying out all night, are two other issues concerning privacy and the family environment. As a courtesy, make sure you ask permission to have overnight
                            guests, and make sure to tell your family when you won't be coming home. You may also have to share one bathroom with the entire rest of the family, you may not get to play your music as loudly as you like it, and you might not get to walk around the house in your underwear. Also, family problems don't disappear just because you're there. Mom may argue with the kids about homework, grandma might go to the hospital; Dad might have trouble at work, etc. You have to be the judge of when it's best to give a family some privacy and not get involved. Make sure to keep the lines of communication open regarding privacy issues. If something bothers you, discuss it calmly and pleasantly with your family.</p>
                    </li>
                    <li><strong>Telephone</strong>
                        <p>Home&ndash;stay families usually have rules about using their telephone. Since the majority of your calls will be long&ndash;distance calls home to family and friends, your home&ndash;stay family won't appreciate expensive phone bills or long conversations that tie up the line. And, it may be too confusing to sort out the telephone bill and have you pay separately for just your calls. Consider buying an international calling card or a cell phone, or try to limit your international communication to e&ndash;mail. For more information on ways to communicate internationally, please see the Communication section of this handbook.</p>
                    </li>
                    <li><strong>Meals</strong>
                        <p>Meals can be one of the biggest challenges. Everyone has different eating habits, likes and dislikes. Plus, you need to give yourself and your stomach time to get used to new food you will be eating in [@country]. In a home&ndash;stay environment, chances are all meals will be prepared for you. Home&ndash;stay is not a restaurant; you will seldom get a choice of what you'd like for breakfast, lunch or dinner. In most cases, you won't even do your own grocery shopping, and you won't even be asked to help cook or serve meals. While not having to go to the market or cook can be a major perk of home&ndash;stay living, it also can have its disadvantages. First of all, authentic home cooking may not always be to your liking (on the other hand, it can be delicious). It may be difficult to tell your host family when you don't like something, knowing they've spent a long time preparing your meal. It can also be difficult to communicate to which foods you're allergic, if you're a vegetarian, or
                            if you don't eat red meat. Meal portions are another issue. Your home&ndash;stay family may feel they are being generous by offering you very large portions of food when you just can't eat that much. Or, your family may not give you as much to eat as you would like. Though you may feel guilty refusing food, or asking for more, it's important to express your needs and be honest. There may also be rules about skipping meals; you may have to give your family prior notice when you won't be home for a meal.</p>
                    </li>
                    <li><strong>Language</strong>
                        <p>The home&ndash;stay environment is the best way to learn Portuguese. Simply put, you will have to communicate with your family on a daily basis. You will be forced to speak with family members, as you cannot remain silent in an active household. Also, there's a good chance your "family" members may not speak a word of English. In trying to make yourself understood, you will no doubt learn fast how to communicate in Portuguese. You have more opportunity to learn in a home&ndash;stay environment than you do in a Residence Hall/Dorm or Apartment where your roommates might be other Americans or English&ndash;speakers. Unlike in a Residence Hall/Dorm or Apartment where you can close yourself up in your room, you interact more with a host family because you are in closer quarters and together more often.</p>
                    </li>
                    <li><strong>Social Network</strong>
                        <p>Your home&ndash;stay family can provide you with a terrific resource: a social connection. They can help you meet new people and introduce you to other relatives your age, etc. Especially in those first few weeks when you don't know too many people, your family can really help you get grounded. Your family will also know where you can go to meet other students and young people: local cafes, discos, etc. They probably have community connections at church, the marketplace, the gym, etc. that might be of interest to you as well. They will also know where you can find the best discounts and bargains in town, which metro and bus routes to take, where to get the freshest bread, etc...</p>
                    </li>
                </ul>
                <div class="img_container"><img alt="home stay" src="images/country_img/housing_homestay.gif"/></div>
            </li>
            <li><strong>Residence Hall/Dorm</strong>
                <p>Life in a Residence Hall/Dorm is like a combination between living with a family and living in an apartment. You will most likely have a room with a bed, desk and closet. You will also probably have communal bathroom and shower facilities, communal cooking and dining facilities, and communal laundry and phone (usually a pay phone) facilities.</p>
                <ul>
                    <li><strong>Privacy and Sharing</strong>
                        <p>You may find your living space cramped, especially if you have to share a room. If you and your roommate clash, sharing a room might also make for tense situation. Also, if you plan to have overnight guests, there may be rules against it, or you may have to ask your roommate for permission. It might take you awhile to get accustomed to the lack of privacy in a residence hall/dorm. Noise level can be another annoyance if you and your roommate have different study schedules or even different tastes in music. Bathroom schedules might conflict; that can be difficult if there is only one shower for every ten students. Kitchen schedules might conflict as well if you have to do your own cooking; the kitchen might get pretty crowned around mealtime when all the students are scrambling for utensils and a spot on the stove. Sharing a phone takes scheduling and patience also. Others may press you to make shorter calls, or you might wish they made shorter ones so you could use the phone. It might
                            be harder for family and friends to reach you as well. Finally, scheduling a laundry time will take patience too. At the end of the week, everyone will have dirty laundry and there might be a long wait until it's your turn.</p>
                    </li>
                    <li><strong>Rules</strong>
                        <p>A lot of students in one place can mean a lot of rules. To keep residence halls/dorms on schedule and running well, there may be a few rules to follow. Just like in a home&ndash;stay environment, you will probably be asked to contribute to your residence hall/dorm by doing some chores. For instance, you and another student partner might be assigned different days to take out the trash, or be in charge of cleaning the communal kitchen or bathroom facilities. Some other common rules are ones that prohibit smoking and drinking, noise after a certain hour, having food in your room, and having overnight guests. Some residence hall/dorms also have a curfew and rules against having the opposite sex in your room. Residence halls/dorms can be co&ndash;ed, all girls or all boys. A residence hall/dorm director may be assigned to each floor, hallway or section of rooms so they can better enforce rules, help you if you need them, and keep an eye on everything. There may be additional rules for laundry,
                            phone, bathroom and dining/kitchen facilities. Before you sign your housing contract, ask your housing advisor about rules and regulations you will be asked to follow, and what the punishments are for breaking the rules.</p>
                    </li>
                    <li><strong>Meals</strong>
                        <p>Instead of cooking for yourself what you want and when you want it, you may have a meal plan with set menus and set hours. Meal plans may be hard to get used to if you don't like the food, if they don't provide enough food, or if you're running late and miss the scheduled meal time hour. Supplementing a meal plan with outside dining can get expensive, so try to stock up on nutritious snacks like fruit instead. Utility expenses will most likely be included.</p>
                    </li>
                    <li><strong>Language and Social Network</strong>
                        <p>Often residence hall/dorms can be very organized and diverse. They are like close&ndash;knit communities of students trying to make the most of their college or university experience. Typically, there will be a large number of student nationals who are from [@country]. They can often be your best guides and teachers; as you interact with them, you practice your language skills and enhance your cultural experience. Communal eating can be like a big family dinner every night where everyone laughs and tells stories about their day. A residence hall/dorm is definitely the place to meet a lot of new people your age and to make international friends. You will hardly ever be alone if you opt to stay in a bustling residence hall/dorm.</p>
                    </li>
                </ul>
                <div class="img_container"><img alt="dorm" src="images/country_img/housing_dorm.gif"/></div>
            </li>
            <li><strong>Apartment</strong>
                <p>You will find that apartment life will give you the most independence, but the most work. If you don't think you can handle paying rent and utilities, paying bills, marketing and cooking for yourself, doing the dishes, doing laundry, cleaning, and working out roommate challenges on your own, then maybe apartment life in [@country] isn't for you. On the other hand, you gain a lot of independence and freedom because you can make your own rules and follow your own schedule.</p>
                <ul>
                    <li><strong>Privacy and Sharing</strong>
                        <p>The amount of privacy you have depends on whether or not you have a roommate(s) and whether or not you share a room with them. Again, there can be challenges if you don't get along with your roommate(s), if you keep different hours, or have different taste in music. Noise can also be a problem, not only with your roommate(s), but with your neighbors as well. If you share appliances like a television, microwave, or even a hairdryer, you might want to work out a schedule of when who uses what. Also, think about whether a co&ndash;ed, all&ndash;guy or all&ndash;girl apartment would work best for you. For example, would you feel comfortable sharing a room or bathroom with a member of the opposite sex?</p>
                    </li>
                    <li><strong>Rules and Responsibility</strong>
                        <p>You are in charge. While this may sound like fun, it can be a challenge to deal with so much responsibility (and often in Portuguese or another language). Remember, bills and leasing contracts might be in Portuguese. You may want to set your own rules in terms of sharing things like food, chores, and even clothes with your roommates. You may also want to talk to your roommate(s) about overnight guests, parties, pets, smoking and curfews. If you or your roommates slack off, no one will be there to enforce rules and make sure chores get done and bills get paid.</p>
                    </li>
                    <li><strong>Meals</strong>
                        <p>Cook what you want, when you want. In an apartment, you won't have to deal with meal plans that have set menus and set hours. If you are a picky eater, or just can't get used to the local cuisine, cooking your own food may be a good thing. However, you also won't have a chef in your kitchen to cook for you and do your dishes as you might in a home&ndash;stay or residence hall/dorm environment. Doing your own grocery shopping also takes time and money; you will have to budget both around your class and travel schedules. No chef will be there to provide a balanced, nutritious meal for you either; you health will be up to you. Try not to get into the habit of eating poorly just because your parents aren't there to tell you to eat your veggies. Instead of microwave meals and junk food, try to enjoy the market&ndash;fresh fruit and vegetables in season and local to your area. Also, experiment with trying to cook local dishes with local ingredients so you don't miss out on [@nationality1]
                            food just because you're cooking for yourself.</p>
                    </li>
                    <li><strong>Language and Social Network</strong>
                        <p>One major disadvantage to living in an apartment is isolation. This can be especially true if you live alone. By living in an apartment, you will have to make an extra effort to get out and meet people and practice your language skills. If your roommate(s) are also from the United States, you may be tempted to always speak in English. Try to seriously avoid spending too much time speaking English with your U.S. roommate(s). Instead, make friends with the locals. You are not studying abroad in order to make friends with other U.S. students and speak English with them. Rather, you chose to study abroad in [@country] in order to have a cultural experience and meet new people. You may want to purposely consider sharing an apartment with local [@nationality1] students rather than other U.S. students. Not only can you practice your language skills with your local roommates, but they can also be great guides and give you lots of helpful advice. Also, local roommates can be of much more help
                            with establishing a social network than other U.S. students can be. Your local roommate(s) will be your main contact with [@nationality1] society and will open the doors for you to meet other locals.</p>
                    </li>
                </ul>
                <div class="img_container"><img alt="apartment" src="images/country_img/housing_apartment.gif"/></div>
            </li>
        </ul>
        <h2><a name="section3"></a>3. Relevant Questions</h2>
        <ul class="relevant_questions">
            <li>What are the pros and cons of living in a home&ndash;stay, residence hall/dorm or apartment environment while in the country of your choice?</li>
            <li>After making a list of pros and cons, which type of housing suits your needs best and why?</li>
            <li>Will you be living in a co&ndash;ed dorm or apartment while in the country of your choice, and does your program permit co&ndash;ed living?</li>
            <li>What can you do to help yourself prepare for the Rules, Privacy, Sharing, Telephone, Meals, Language and Social Network aspects of the type of housing you have chosen?</li>
            <li>Can you change your place of residence in the country of your choice if things don't work out?</li>
        </ul>
        <h2><a name="section4"></a>4. Checklist</h2>
        <ul class="checklists">
            <li>I have made a list of the pros and cons of each type of housing available to me abroad.</li>
            <li>I have asked a study abroad administrator if I can change my place of residence abroad in the event that things don't work out.</li>
            <li>After making a list of pros and cons, I have decided which type of housing suits my needs best and why.</li>
            <li>I realize that it may take time for me to adjust to the Rules, Privacy, Sharing, Telephone, Meals, Language and Social Network aspects of the type of housing I have chosen.</li>
        </ul>
        <h2><a name="section5"></a>5. Resources</h2>
        <ul>
            <li><a href="http://allabroad.us/results.php?group_select=on&amp;query=housing">AllAbroad.us &ndash; Housing</a>: Hear from mentors common questions and answer students have about host families and housing abroad.</li>
        </ul>
        <div class="top"><a href="#top">Back to Top</a></div>
    </div>
</div>
